apiVersion: apps/v1
kind: Deployment
metadata:
  name: p1
spec:
  selector:
    matchLabels:
      app: p1
  template:
    metadata:
      labels:
        app: p1
    spec:
      nodeName: multinode-m02
      containers:
      - name: p1
        image: rminz/cpuload:v2
        resources:
          requests:
            memory: "128Mi"
            cpu: "4000m"
