apiVersion: apps/v1
kind: Deployment
metadata:
  name: limit
spec:
  selector:
    matchLabels:
      app: limit
  template:
    metadata:
      labels:
        app: limit
    spec:
      nodeName: multinode-m02
      containers:
      - name: limit
        image: rminz/cpuload:v2
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
